export interface ConceptCoverage {
  readonly desktop: `L${string}`;
  readonly mobile: `L${string}`;
  readonly route: string;
  readonly state: string;
  readonly comparison: readonly [string, string, string, string, string, string];
}

type ComparisonNotes = ConceptCoverage['comparison'];

const compare = (
  composition: string,
  density: string,
  typography: string,
  hierarchy: string,
  interaction: string,
  responsive: string,
): ComparisonNotes => [
  `composition: ${composition}`,
  `density: ${density}`,
  `typography: ${typography}`,
  `hierarchy: ${hierarchy}`,
  `interaction state: ${interaction}`,
  `responsive behavior: ${responsive}`,
];

const conceptComparisons = {
  'L01-L02': compare(
    'shared board is centered between two participant rails under a single turn banner',
    'clock, score, actor attribution, board evidence, and input remain visible together',
    'condensed player labels contrast with monospaced clock and score records',
    'current actor and durable clock lead; forfeit and secondary match facts recede',
    'player-owned input is explicit and waiting state disables the keyboard without hiding it',
    'participant rails collapse while the turn banner, shared board, keyboard, and dock stack in flow',
  ),
  'L03-L04': compare(
    'Lobby-first COMBAT workspace keeps tabs, queue action, public rooms, and active handoff in one ledger',
    'queue status and room metadata use ruled rows instead of promotional cards',
    'large COMBAT title is paired with compact mode, privacy, and population records',
    'matchmaking action leads, then joinable rooms, then explanatory capability context',
    'queue and cancel are mutually exclusive; lobby join and leave actions stay literal',
    'desktop context rail becomes stacked disclosures below the mobile lobby register',
  ),
  'L05-L06': compare(
    'ranked verdict, score split, rating movement, and rematch routes share one centered result ledger',
    'exact points and rating deltas stay adjacent to the outcome rather than in detached summaries',
    'verdict display type is restrained by monospaced before-and-after rating values',
    'outcome leads, settlement proof follows, and rematch or exit actions close the sequence',
    'result state names win or loss beyond color and separates rematch from navigation',
    'wide score columns collapse into a vertical verdict stack without changing settlement order',
  ),
  'L07-L08': compare(
    'OG and GO are equal entry gates above four Daily and Practice starts plus resume rows',
    'format differences, active sessions, and route handoffs are visible without opening a wizard',
    'oversized OG and GO marks anchor concise monospaced setup details',
    'format choice leads; active games and recent-result disclosures remain subordinate',
    'each start names mode and scope, while resume actions point to the existing session',
    'two desktop gates stack as complete mobile entrances ahead of resumable state',
  ),
  'L09-L10': compare(
    'month grid is paired with a Daily status rail and four mode lanes per selected date',
    'date cells encode availability compactly while coin rules and streak context stay nearby',
    'calendar numerals use mono rhythm beneath condensed month and lane headings',
    'selected date and playable lanes lead; archive rules and streaks are secondary',
    'today, past unlock, completed, and unavailable states use labels and marks beyond color',
    'month navigation remains horizontal while the status rail moves below the mobile grid',
  ),
  'L11-L12': compare(
    'newest-first five-column record is anchored by a compact three-axis filter register',
    'result, details, context, and completion time remain scan-aligned in ruled rows',
    'condensed game labels and monospaced result metadata preserve ledger rhythm',
    'record count and filters precede results; no decorative result card outranks history',
    'filter selections apply immediately and win, loss, and draw are named textually',
    'wide records gain controlled horizontal containment while filters recompose above them',
  ),
  'L13-L14': compare(
    'private Solo metrics, progression, and multiplayer rating tracks occupy separate ruled groups',
    'win rate, game count, streak, XP, and ratings are visible in compact metric bands',
    'large numeric metrics sit above small condensed labels and exact mono records',
    'private performance leads; the public leaderboard remains a direct but secondary handoff',
    'signed-out and local-only authority are stated instead of inferred from missing data',
    'four-up desktop metrics retain scan order as a compact mobile grid and vertical ledger',
  ),
  'L15-L16': compare(
    'identity editor, sanctioned public preview, and account boundary occupy distinct sections',
    'display name, handle, visibility, and save state stay within one short form ledger',
    'profile display type is balanced by monospaced immutable identifier context',
    'editable public projection leads while raw-auth and private-data boundaries remain explanatory',
    'save acknowledgement is explicit and public preview never exposes email or raw auth ID',
    'desktop edit and preview columns become one ordered mobile form without field loss',
  ),
  'L17-L18': compare(
    'owned Practice tools lead above a fixed-price purchase register and progression context',
    'effect samples, inventory counts, price, balance, and shortfall fit in each ruled offer',
    'coin values use mono emphasis beneath condensed answer-safe tool names',
    'inventory and safe effect explanation precede purchase decisions and Stats handoff',
    'buyable and insufficient-balance states are literal; no real-money metaphor is introduced',
    'two-column offers stack and keep the compact balance decision visible on mobile',
  ),
  'L19-L20': compare(
    'search and word list occupy the primary column with curated definition detail beside them',
    'word length, definition availability, selection, and fallback route remain visible together',
    'searched words use condensed display while definitions and source notes use readable mono text',
    'search result selection leads, curated detail follows, and external fallback is last',
    'copy and explicit Google-search fallback require user action and reveal no private context',
    'the detail pane moves beneath search results and keeps a bounded mobile reading width',
  ),
  'L21-L22': compare(
    'settings index anchors grouped gameplay, accessibility, sound, privacy, and update controls',
    'segmented choices and switches use short ruled rows with current values always visible',
    'section labels use condensed caps while current preferences remain monospaced and literal',
    'accessibility and gameplay preferences lead before account and reset consequences',
    'controls expose selected state, reduced-motion intent, and confirmation for destructive reset',
    'desktop index becomes a horizontal mobile index while groups remain in document order',
  ),
  'L23-L24': compare(
    'tutorial step rail frames one playable lesson with evidence legend and next action',
    'instruction, sample tiles, keyboard rule, and progress remain within a single lesson view',
    'lesson title uses editorial condensed type with terse monospaced rule explanations',
    'current lesson and its interaction lead; help index and later topics remain secondary',
    'step completion and next or previous controls are explicit and keyboard reachable',
    'numbered desktop steps compress to a mobile progress spine above the lesson',
  ),
  'L25-L26': compare(
    'two route gates, exact local resume, Today register, and guest context reproduce the command hub',
    'all four Today routes remain visible before the mobile dock while desktop progress stays in a right rail',
    'large route names use condensed display and resume or status detail stays monospaced',
    'guest choice leads, local resume follows, and sign-in remains optional context',
    'Solo remains available while account-owned COMBAT is explicitly hidden for the guest',
    'desktop right rail becomes compact in-flow progress and privacy bands after the mobile route ledger',
  ),
  'L27-L28': compare(
    'read-only shared board is framed by participant score context and a spectator header',
    'actor rows, scores, freshness, and spectator restriction remain visible without input controls',
    'player labels and live score use condensed type with monospaced observation metadata',
    'live match evidence leads while join, edit, or answer controls are intentionally absent',
    'spectator state is named read-only and Daily privacy exclusion remains explicit',
    'participant rails collapse into the header while the shared board fills the mobile stream',
  ),
  'L29-L31': compare(
    'GO chain spine, seven-column board, keyboard, and session tools retain the locked gameplay order',
    'chain position, exact setup, six attempts, board, full keyboard, and legend fit in one active scan',
    'condensed tile letters and headings pair with mono validation and attempt messages',
    'board and owned input lead; inventory and game controls stay below the active workspace',
    'physical and on-screen keys converge on one reducer and invalid attempts announce without consumption',
    'desktop side spine compresses to numbered in-flow chain context above the mobile board and safe-area dock',
  ),
  'L30-L32': compare(
    'Focus Mode preserves the same board and chain while removing peripheral navigation and tool rail',
    'only active puzzle context, attempts, evidence, keyboard, and exit affordance remain',
    'quiet condensed context and mono evidence use the same scale as regular play',
    'puzzle interaction becomes the sole hero and Exit focus remains consistently discoverable',
    'focus query changes presentation only; Escape and the explicit button restore the same session',
    'mobile Focus removes the dock and spine rather than creating a second game implementation',
  ),
  'L33-L34': compare(
    'terminal verdict, exact accepted guesses, reward context, and definition or history handoffs replace active input',
    'result facts and continuation actions stay compact without retaining a dominant dead keyboard',
    'verdict display type is paired with monospaced counts and answer metadata',
    'completion and deterministic next session lead; copy and historical routes are subordinate',
    'won or ended state is named, saved before confirmation, and exposes a deliberate next action',
    'desktop result region collapses into one naturally scrolling mobile verdict ledger',
  ),
  'L35-L36': compare(
    'eight-letter shared GO board keeps actor attribution within the board rather than widening participant chrome',
    'long rows, chain position, score, clock, and keyboard remain bounded inside the game region',
    'tile type compacts before surrounding status text, preserving character legibility',
    'shared evidence remains primary and long-word stress never displaces turn authority',
    'actor and evidence states remain named even as tile width contracts',
    'mobile tiles compact within the viewport while the page itself remains free of horizontal overflow',
  ),
  'L37-L38': compare(
    'three-letter timed OG board stays centered instead of inflating tiles to fill the shell',
    'clock, turn, score, compact rows, and complete keyboard preserve normal information density',
    'short-word tiles keep the same condensed letter system and mono timing record',
    'durable clock and actor lead; the small board does not become decorative hero imagery',
    'timeout and waiting ownership remain explicit around the compact input surface',
    'mobile keeps bounded tile size and centers the short board above the standard keyboard',
  ),
  'L39-L40': compare(
    'Daily asynchronous match exposes UTC date, actor turn, durable state, and return path in one ledger',
    'last move, remaining time, score, puzzle state, and opponent wait status stay adjacent',
    'UTC and clock facts use mono records beneath condensed Daily and player labels',
    'durable turn state leads; Realtime freshness and return navigation remain supporting context',
    'non-owner input is disabled and waiting survives reload rather than relying on presence',
    'desktop match rails collapse into a mobile status band above the same shared board',
  ),
  'L41-L42': compare(
    'timeout verdict and clock-expiry evidence precede score and settlement details',
    'exact expired actor, terminal timestamp, rating effect, and next routes share one compact record',
    'red timeout heading is reinforced by literal mono timeout and clock labels',
    'terminal precedence leads before rematch or history actions',
    'timeout is irreversible in the view and is distinguished from forfeit or cancellation',
    'wide evidence columns become an ordered mobile timeout ledger with the verdict retained first',
  ),
  'L43-L44': compare(
    'forfeit verdict identifies the actor and post-start condition above settlement consequences',
    'score, rating effect, participant state, and exit routes stay in one ruled result surface',
    'literal FORFEIT text supports red state styling and mono settlement facts',
    'forfeit reason leads and rematch remains secondary to recorded outcome',
    'confirmation precedes the action and the terminal state cannot be confused with timeout',
    'mobile stacks actor, consequence, and route actions without changing precedence',
  ),
  'L45-L46': compare(
    'neutral cancellation ledger replaces competitive celebration when no accepted guess exists',
    'canceller, pre-guess proof, rating neutrality, and return route are all visible',
    'muted condensed verdict and mono yes-no facts avoid trophy or weapon symbolism',
    'no-contest status leads; rating and score neutrality follow as proof',
    'cancelled is distinct from forfeit and exposes no winner or invented reward',
    'desktop fact table becomes a short mobile cancellation stack above one return action',
  ),
  'L47-L48': compare(
    'refresh scope, upstream identity, atomic manifest rule, and confirm or cancel actions share one dialog ledger',
    'the irreversible boundary and expected object paths remain visible before authorization',
    'condensed operation heading pairs with monospaced scope and revision facts',
    'consequence and authorization lead; confirmation action follows only after review',
    'confirm and cancel are explicit and no refresh begins from route entry alone',
    'desktop confirmation panel becomes a full-width mobile sheet with actions in safe reach',
  ),
  'L49-L50': compare(
    'denial mark and role-first explanation occupy the center without leaking dashboard content',
    'required role, observed authorization class, and safe return fit in a terse alert',
    'red Access denied display is backed by literal mono authorization facts',
    'denial leads; no operational controls or private diagnostics appear beneath it',
    'authenticated non-admin remains blocked before any admin data or API action loads',
    'desktop mark-and-message columns become one centered mobile denial stack',
  ),
  'L51-L52': compare(
    'single operation status band holds progress, stage, elapsed context, and disabled control state',
    'validation and upload stages remain legible without fabricated percentage precision',
    'condensed Refresh in progress text pairs with mono stage and timing records',
    'truthful in-flight status leads and prior dashboard data remains secondary',
    'repeat submission is disabled while the bounded request is active',
    'wide status band stacks its mark, stage, and disabled action on mobile',
  ),
  'L53-L54': compare(
    'success receipt places new revision metadata beside validated lengths and pointer result',
    'duration, object count, revision, manifest swap, and follow-up action remain in one receipt',
    'green success display is reinforced by mono receipt fields and timestamps',
    'accepted manifest pointer leads; supporting upload facts and return action follow',
    'success is acknowledged only after the bounded API receipt and exposes no secret values',
    'two-column receipt fields become a single mobile ledger while the success banner stays first',
  ),
  'L55-L56': compare(
    'failure banner and preserved-pointer proof precede diagnostic facts and safe retry',
    'failed stage, error class, prior revision, and cleanup implication are visible together',
    'red failure heading is backed by literal mono error and unchanged-pointer records',
    'integrity of the prior manifest leads; retry remains subordinate and deliberate',
    'failure never claims partial success and retry does not overwrite another actor pointer',
    'desktop diagnostics stack beneath the failure banner on mobile with no clipped error text',
  ),
  'L57-L58': compare(
    'anonymous admin entry shows authentication boundary and a single sign-in route',
    'no operational metadata is rendered before identity is established',
    'neutral lock and condensed authentication heading avoid implying a server failure',
    'sign-in requirement leads while Admin diagnostics remain entirely absent',
    'anonymous differs explicitly from authenticated denial and unconfigured environment states',
    'desktop lock composition collapses to a compact mobile sign-in stack',
  ),
  'L59-L60': compare(
    'environment-unconfigured state identifies missing safe configuration without exposing names or values',
    'deployment scope, unavailable capability, and safe return are the only visible facts',
    'amber operational heading pairs with monospaced environment-scope language',
    'configuration boundary leads and refresh controls remain absent',
    'state fails closed before auth or admin mutation and never suggests client-side secrets',
    'desktop explanation becomes a single mobile operations notice with no fake gate',
  ),
  'L61-L62': compare(
    'Operational Dashboard combines source health, served lengths, current revision, activity, and refresh entry',
    'four status metrics and recent operations remain scan-aligned without exposing private payloads',
    'large health values sit above condensed labels and monospaced revision metadata',
    'health and current pointer lead; activity and refresh confirmation handoff follow',
    'dashboard is available only in the authorized visual state and refresh still requires confirmation',
    'four desktop metrics reflow to a two-column mobile matrix above activity rows',
  ),
  'L63-L64': compare(
    'loading, offline, update-ready, route recovery, and notification bands share one restrained system language',
    'each state exposes one cause, one continuity fact, and at most one primary recovery action',
    'condensed system headings pair with readable mono continuity and retry text',
    'continuity of saved Solo state leads before retry, update, or dismiss actions',
    'status is announced live, update remains prompt-controlled, and route failure offers an explicit retry',
    'desktop bands become compact mobile notices above the safe-area dock without blocking the main landmark',
  ),
} as const;

export const conceptCoverage: readonly ConceptCoverage[] = [
  {
    desktop: 'L01',
    mobile: 'L02',
    route: '/combat/match/:matchId',
    state: 'active gameplay shell',
    comparison: conceptComparisons['L01-L02'],
  },
  {
    desktop: 'L03',
    mobile: 'L04',
    route: '/combat/lobby',
    state: 'Lobby-first hub',
    comparison: conceptComparisons['L03-L04'],
  },
  {
    desktop: 'L05',
    mobile: 'L06',
    route: '/combat/match/:matchId/result',
    state: 'ranked points result',
    comparison: conceptComparisons['L05-L06'],
  },
  {
    desktop: 'L07',
    mobile: 'L08',
    route: '/play',
    state: 'Solo overview',
    comparison: conceptComparisons['L07-L08'],
  },
  {
    desktop: 'L09',
    mobile: 'L10',
    route: '/calendar',
    state: 'Daily Calendar',
    comparison: conceptComparisons['L09-L10'],
  },
  {
    desktop: 'L11',
    mobile: 'L12',
    route: '/history',
    state: 'unified completed History',
    comparison: conceptComparisons['L11-L12'],
  },
  {
    desktop: 'L13',
    mobile: 'L14',
    route: '/stats',
    state: 'private stats and public handoff',
    comparison: conceptComparisons['L13-L14'],
  },
  {
    desktop: 'L15',
    mobile: 'L16',
    route: '/profile',
    state: 'profile editor',
    comparison: conceptComparisons['L15-L16'],
  },
  {
    desktop: 'L17',
    mobile: 'L18',
    route: '/marketplace',
    state: 'inventory and purchase register',
    comparison: conceptComparisons['L17-L18'],
  },
  {
    desktop: 'L19',
    mobile: 'L20',
    route: '/word-explorer',
    state: 'definition console',
    comparison: conceptComparisons['L19-L20'],
  },
  {
    desktop: 'L21',
    mobile: 'L22',
    route: '/settings',
    state: 'preference ledger',
    comparison: conceptComparisons['L21-L22'],
  },
  {
    desktop: 'L23',
    mobile: 'L24',
    route: '/help',
    state: 'guided tutorial',
    comparison: conceptComparisons['L23-L24'],
  },
  {
    desktop: 'L25',
    mobile: 'L26',
    route: '/',
    state: 'guest Home command hub',
    comparison: conceptComparisons['L25-L26'],
  },
  {
    desktop: 'L27',
    mobile: 'L28',
    route: '/combat/live/:matchId',
    state: 'read-only spectator',
    comparison: conceptComparisons['L27-L28'],
  },
  {
    desktop: 'L29',
    mobile: 'L31',
    route: '/play/practice/go',
    state: 'regular Solo play',
    comparison: conceptComparisons['L29-L31'],
  },
  {
    desktop: 'L30',
    mobile: 'L32',
    route: '/play/practice/go?focus=1',
    state: 'Focus Mode',
    comparison: conceptComparisons['L30-L32'],
  },
  {
    desktop: 'L33',
    mobile: 'L34',
    route: '/play/practice/go',
    state: 'Solo result handoff',
    comparison: conceptComparisons['L33-L34'],
  },
  {
    desktop: 'L35',
    mobile: 'L36',
    route: '/combat/match/:matchId',
    state: 'eight-letter GO stress',
    comparison: conceptComparisons['L35-L36'],
  },
  {
    desktop: 'L37',
    mobile: 'L38',
    route: '/combat/match/:matchId',
    state: 'three-letter timed OG stress',
    comparison: conceptComparisons['L37-L38'],
  },
  {
    desktop: 'L39',
    mobile: 'L40',
    route: '/combat/match/daily-proof',
    state: 'ranked Daily asynchronous',
    comparison: conceptComparisons['L39-L40'],
  },
  {
    desktop: 'L41',
    mobile: 'L42',
    route: '/combat/match/:matchId/result?outcome=timeout',
    state: 'timeout precedence',
    comparison: conceptComparisons['L41-L42'],
  },
  {
    desktop: 'L43',
    mobile: 'L44',
    route: '/combat/match/:matchId/result?outcome=forfeit',
    state: 'post-start forfeit',
    comparison: conceptComparisons['L43-L44'],
  },
  {
    desktop: 'L45',
    mobile: 'L46',
    route: '/combat/match/:matchId/result?outcome=cancelled',
    state: 'pre-guess cancellation',
    comparison: conceptComparisons['L45-L46'],
  },
  {
    desktop: 'L47',
    mobile: 'L48',
    route: '/admin?visual=confirm',
    state: 'refresh confirmation',
    comparison: conceptComparisons['L47-L48'],
  },
  {
    desktop: 'L49',
    mobile: 'L50',
    route: '/admin?visual=denied',
    state: 'non-admin denied',
    comparison: conceptComparisons['L49-L50'],
  },
  {
    desktop: 'L51',
    mobile: 'L52',
    route: '/admin?visual=inflight',
    state: 'refresh in flight',
    comparison: conceptComparisons['L51-L52'],
  },
  {
    desktop: 'L53',
    mobile: 'L54',
    route: '/admin?visual=success',
    state: 'refresh success',
    comparison: conceptComparisons['L53-L54'],
  },
  {
    desktop: 'L55',
    mobile: 'L56',
    route: '/admin?visual=failure',
    state: 'refresh failure',
    comparison: conceptComparisons['L55-L56'],
  },
  {
    desktop: 'L57',
    mobile: 'L58',
    route: '/admin?visual=anonymous',
    state: 'anonymous denied',
    comparison: conceptComparisons['L57-L58'],
  },
  {
    desktop: 'L59',
    mobile: 'L60',
    route: '/admin?visual=unconfigured',
    state: 'environment unconfigured',
    comparison: conceptComparisons['L59-L60'],
  },
  {
    desktop: 'L61',
    mobile: 'L62',
    route: '/admin?visual=ready',
    state: 'Operational Dashboard',
    comparison: conceptComparisons['L61-L62'],
  },
  {
    desktop: 'L63',
    mobile: 'L64',
    route: '*',
    state: 'loading, offline, recovery, and notifications',
    comparison: conceptComparisons['L63-L64'],
  },
];

export const coveredConceptIds = new Set(
  conceptCoverage.flatMap(({ desktop, mobile }) => [desktop, mobile]),
);
